services:
  - type: web
    name: union-ai-assistant
    env: python
    plan: free
    region: ohio
    pythonVersion: "3.10"  # More compatible than 3.13
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --only-binary :all: --no-cache-dir -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm --workers=1 --threads=4 --timeout 120 app:app
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: HUGGINGFACEHUB_API_TOKEN
        value:  ''#  Set in Render dashboard